'use strict';
/**
 * Shared category data used by both .menu and .help
 *
 * Each entry:
 *   slug       — short keyword user types  (.menu movies  /  .help ai)
 *   emoji      — category emoji
 *   title      — display title
 *   cmds[]     — command list shown by .menu <slug>
 *   help[]     — detailed description lines shown by .help <slug>
 */

const CATEGORIES = [
    {
        slug: 'start',
        emoji: '🚀',
        title: 'START HERE',
        cmds: [
            '.ping', '.alive', '.uptime',
            '.menu', '.help',
            '.owner', '.update', '.autoupdate',
            '.calc', '.settings', '.sudo',
        ],
        help: [
            '.ping                 → check if bot is online',
            '.alive                → bot status message',
            '.uptime               → how long bot has been running',
            '.menu                 → category overview',
            '.menu <category>      → commands in a category',
            '.help                 → this help overview',
            '.help <category>      → full descriptions for a category',
            '.owner                → contact bot owner',
            '.update               → update bot to latest version',
            '.autoupdate on/off    → automatic updates',
            '.calc <expr>          → 🧮 calculator  (e.g. .calc 5*9+2)',
            '.settings             → view bot settings',
            '.sudo                 → owner-only sudo mode',
        ],
    },
    {
        slug: 'ai',
        emoji: '🤖',
        title: 'AI COMMANDS',
        cmds: [
            '.ai <query>', '.ask <query>',
            '.gpt <query>', '.gpt4o <query>', '.gptlarge <query>', '.gptfast <query>',
            '.gemini <query>', '.mistral <query>', '.qwen <query>',
            '.imagine <prompt>', '.flux <prompt>', '.txt2img <prompt>',
            '.sora <prompt>',
        ],
        help: [
            '.ai <query>           → GPT-4o AI (general purpose)',
            '.ask <query>          → alias for .ai',
            '.gpt <query>          → GPT-4o via Pollinations (free)',
            '.gpt4o <query>        → GPT-4o advanced',
            '.gptlarge <query>     → GPT-4o Large (more detailed)',
            '.gptfast <query>      → GPT-4o Fast (quicker)',
            '.gemini <query>       → Google Gemini AI',
            '.mistral <query>      → Mistral AI',
            '.qwen <query>         → Qwen Coder AI',
            '.imagine <prompt>     → AI image generation (Flux)',
            '.flux <prompt>        → Flux image generator',
            '.txt2img <prompt>     → text-to-image',
            '.sora <prompt>        → Cinematic AI image',
            '',
            '🆓 All AI commands use Pollinations.ai — completely free!',
        ],
    },
    {
        slug: 'movies',
        emoji: '🎬',
        title: 'MOVIES & STREAMING',
        cmds: [
            '.movie <title>', '.movie details <id>',
            '.movie dl <id>', '.movie dl <id> 360p',
            '.movietrailer <id>',
            '.trending', '.upcoming', '.schedule',
            '.live', '.livesearch <name>', '.livestream <id>',
            '.anime <title>', '.anime dl <id>',
            '.net9ja <title>',
        ],
        help: [
            '.movie <title>            → search any movie or show',
            '.movie details <id>       → full info + poster image',
            '.movie dl <id>            → show available resolutions',
            '.movie dl <id> 360p       → download by quality name',
            '.movietrailer <id>        → watch official trailer 🎬',
            '.trending                 → 🔥 what is trending now',
            '.upcoming                 → 🗓 upcoming releases',
            '.schedule                 → 📅 weekly airing schedule',
            '.live                     → browse live TV channels',
            '.livesearch <name>        → search a live channel',
            '.livestream <id>          → get stream link',
            '.anime <title>            → search anime titles',
            '.anime dl <id>            → anime download options',
            '.net9ja <title>           → search Net9ja movie database',
        ],
    },
    {
        slug: 'download',
        emoji: '📥',
        title: 'DOWNLOADERS',
        cmds: [
            '.play <title/url>', '.song <title/url>',
            '.video <title/url>', '.ytmp4 <url>',
            '.tiktok <url>', '.tt <url>',
            '.instagram <url>', '.insta <url>',
            '.facebook <url>', '.fb <url>',
            '.spotify <title/url>',
            '.apk <app name>',
            '.gitclone <github url>',
        ],
        help: [
            '.play / .song <title> → YouTube audio (MP3) via GiftedTech',
            '.video / .ytmp4 <url> → YouTube video (MP4)',
            '.tiktok / .tt <url>   → TikTok video without watermark',
            '.instagram <url>      → Instagram post / reel',
            '.facebook <url>       → Facebook video',
            '.spotify <title/url>  → Spotify track download',
            '.apk <app name>       → Download APK by app name',
            '.gitclone <url>       → Download GitHub repo as ZIP',
        ],
    },
    {
        slug: 'search',
        emoji: '🔍',
        title: 'SEARCH',
        cmds: [
            '.yts <query>', '.ytsearch <query>',
            '.wallpaper <query>',
            '.pinterest <query>',
            '.lyrics <song>',
            '.news',
        ],
        help: [
            '.yts / .ytsearch <q>  → search YouTube videos (top 7 results)',
            '.wallpaper <query>    → high-quality wallpaper images',
            '.pinterest <query>    → Pinterest image search',
            '.lyrics <song>        → song lyrics lookup',
            '.news                 → latest tech news headlines',
        ],
    },
    {
        slug: 'stalk',
        emoji: '🌐',
        title: 'STALK / LOOKUP',
        cmds: [
            '.ttstalk <username>', '.tiktokstalk <username>',
            '.ghstalk <username>',
            '.igstalk <username>',
            '.twstalk <username>', '.xstalk <username>',
            '.steamstalk <username>',
        ],
        help: [
            '.ttstalk <user>     → TikTok profile lookup (followers, videos, bio)',
            '.ghstalk <user>     → GitHub profile lookup (repos, followers)',
            '.igstalk <user>     → Instagram profile lookup',
            '.twstalk <user>     → Twitter / X profile lookup',
            '.steamstalk <user>  → Steam gaming profile lookup',
        ],
    },
    {
        slug: 'sports',
        emoji: '🏆',
        title: 'SPORTS',
        cmds: [
            '.sports', '.scoreboard', '.livescores',
            '.sportsteam <name>', '.sportsplayer <name>',
            '.nbastandings', '.nflstandings', '.soccerstandings',
            '.news',
        ],
        help: [
            '.sports / .scoreboard      → live soccer, NBA & NFL scores',
            '.livescores                → alias for .sports',
            '.sportsteam <name>         → look up a sports team',
            '.sportsplayer <name>       → look up a sports player',
            '.nbastandings              → NBA league standings',
            '.nflstandings              → NFL league standings',
            '.soccerstandings           → soccer league standings',
            '.news                      → latest tech & general news',
        ],
    },
    {
        slug: 'tools',
        emoji: '🔧',
        title: 'TOOLS & UTILITIES',
        cmds: [
            '.weather <city>', '.translate <text>',
            '.tts <text>', '.url <link>',
            '.ss <url>',
            '.createqr <text>', '.genqr <text>',
            '.carbon <code>',
            '.imgscan', '.remini', '.removebg',
            '.fact',
            '.tempmail', '.tempmail inbox',
            '.cpuinfo', '.meminfo', '.diskinfo', '.timezone',
        ],
        help: [
            '.weather <city>        → current weather & forecast',
            '.translate <text>      → auto-detect & translate',
            '.tts <text>            → text to speech audio',
            '.url <link>            → upload file to URL',
            '.ss <url>              → screenshot a website',
            '.createqr <text>       → generate QR code image',
            '.carbon <code>         → code snippet to image',
            '.imgscan               → AI image identification (reply to image)',
            '.remini                → enhance / upscale image quality',
            '.removebg              → remove image background',
            '.fact                  → random fun fact',
            '.tempmail              → generate temporary email address',
            '.tempmail inbox        → check temp email inbox',
            '.cpuinfo / .meminfo    → system resource usage',
            '.diskinfo / .timezone  → disk & time info',
        ],
    },
    {
        slug: 'fun',
        emoji: '😄',
        title: 'FUN & SOCIAL',
        cmds: [
            '.truth', '.dare', '.rizz', '.joke', '.quote', '.meme',
            '.flirt @user', '.compliment @user', '.insult @user',
            '.ship @u1 @u2', '.simp @user',
            '.pair', '.unpair',
            '.8ball <question>',
            '.tictactoe @user', '.hangman', '.trivia',
            '.goodnight', '.shayari', '.roseday',
            '.waifu', '.bored', '.activity',
        ],
        help: [
            '.truth                → random truth question',
            '.dare                 → random dare challenge',
            '.rizz / .pickupline  → 😏 rizz / pickup lines',
            '.joke                 → random joke',
            '.quote                → wisdom or motivational quote',
            '.meme                 → random meme image',
            '.waifu                → random anime waifu image',
            '.bored / .activity   → random activity when bored',
            '.flirt @user          → flirt message at a user',
            '.compliment @user     → send a compliment',
            '.insult @user         → friendly roast',
            '.ship @u1 @u2         → compatibility percentage',
            '.simp @user           → simp rating card',
            '.pair / .unpair       → couple pairing system',
            '.8ball <question>     → magic 8-ball answer',
            '.tictactoe @user      → play tic-tac-toe',
            '.hangman              → play hangman',
            '.trivia               → trivia question',
            '.goodnight            → goodnight message',
            '.shayari              → Urdu shayari poetry',
            '.roseday              → Rose Day message',
        ],
    },
    {
        slug: 'gaming',
        emoji: '🎮',
        title: 'GAMING SENSITIVITY',
        cmds: [
            '.freefiresensi <device> [RAM]GB <Android|iOS>',
            '.pubgsensi <device> [RAM]GB <Android|iOS>',
            '.codmsensi <device> [RAM]GB <Android|iOS>',
            '.bssensi <device> [RAM]GB <Android|iOS>',
        ],
        help: [
            '.freefiresensi <device> [RAM]GB <Android|iOS>',
            '   → Free Fire sensitivity (General, Red Dot, 2x-4x Scope, Sniper, Free Look, DPI)',
            '',
            '.pubgsensi <device> [RAM]GB <Android|iOS>',
            '   → PUBG Mobile sensitivity (Camera 3rd/1st person, 6 scope levels, ADS, Gyroscope)',
            '',
            '.codmsensi <device> [RAM]GB <Android|iOS>',
            '   → Call of Duty Mobile sensitivity (Firing Camera, ADS 1x-Sniper, Gyroscope)',
            '',
            '.bssensi <device> [RAM]GB <Android|iOS>',
            '   → Blood Strike sensitivity (Camera, ADS Red Dot-Sniper, Gyroscope)',
            '',
            'RAM is optional on all commands — defaults to 6 GB if not given.',
            'Examples:',
            '  .pubgsensi Samsung S23 Ultra 12GB Android',
            '  .codmsensi iPhone 15 Pro Max iOS',
            '  .bssensi POCO X6 Pro Android',
        ],
    },
    {
        slug: 'stickers',
        emoji: '🖼️',
        title: 'STICKERS & IMAGE EFFECTS',
        cmds: [
            '.sticker / .s', '.attp <text>', '.emojimix <e1> <e2>',
            '.steal', '.tgsticker',
            '.blur', '.enhance', '.remini', '.removebg',
            '.screenshot <url>',
            '.1917', '.arena', '.blackpink', '.circle', '.comrade',
            '.devil', '.fire', '.gay', '.glass', '.glitch', '.hacker',
            '.heart', '.horny', '.ice', '.impressive', '.jail',
            '.leaves', '.lgbt', '.light', '.lolice', '.matrix',
            '.metallic', '.namecard', '.neon', '.passed',
            '.snow', '.stupid', '.thunder', '.triggered', '.waste',
        ],
        help: [
            '.sticker / .s         → convert image/video to sticker',
            '.attp <text>          → animated text sticker',
            '.emojimix <e1> <e2>   → mix two emojis into one sticker',
            '.steal                → steal sticker from message',
            '.tgsticker            → search Telegram sticker pack',
            '.blur                 → blur an image',
            '.enhance              → AI enhance / upscale image',
            '.remini               → Remini AI photo enhancer',
            '.removebg             → remove image background',
            '.screenshot <url>     → screenshot a website',
            '.fire/.ice/.neon      → add effects to images',
            '.glitch/.matrix       → special effects',
            '+ more effects        → run .menu stickers to see all',
        ],
    },
    {
        slug: 'crypto',
        emoji: '💰',
        title: 'CRYPTO',
        cmds: [
            '.crypto-price <coin>',
            '.top-crypto',
            '.trending-crypto',
            '.crypto-convert <amt> <from> <to>',
        ],
        help: [
            '.crypto-price <coin>               → live coin price',
            '.top-crypto                        → top 10 coins by market cap',
            '.trending-crypto                   → 🔥 trending coins',
            '.crypto-convert <amt> <from> <to>  → convert between coins',
        ],
    },
    {
        slug: 'anime',
        emoji: '🎌',
        title: 'ANIME',
        cmds: [
            '.animu', '.character', '.waifu',
            '.animeinfo <title>', '.trendinganime', '.animeindo <title>',
        ],
        help: [
            '.animu                  → random anime image / GIF sticker',
            '.character              → anime character info',
            '.waifu                  → random waifu image',
            '.animeinfo <title>      → detailed anime info (score, genres, synopsis)',
            '.trendinganime          → 🔥 top currently-airing anime',
            '.animeindo <title>      → search Indonesian-dubbed anime',
            '',
            '💡 For streaming anime use .anime <title>  (in Movies)',
        ],
    },
    {
        slug: 'tempgen',
        emoji: '📲',
        title: 'TEMP MAIL',
        cmds: ['.tempmail', '.tempmail inbox'],
        help: [
            '.tempmail              → generate a temporary email address',
            '.tempmail inbox        → check inbox of temp email',
        ],
    },
    {
        slug: 'language',
        emoji: '📖',
        title: 'LANGUAGE & DEFINE',
        cmds: [
            '.define <word>', '.synonym <word>', '.antonym <word>', '.wordofday',
            '.wiki <topic>', '.wikipedia <topic>',
            '.urban <word>',
        ],
        help: [
            '.define <word>         → dictionary definition + example',
            '.synonym <word>        → synonyms list',
            '.antonym <word>        → antonyms list',
            '.wordofday             → word of the day',
            '.wiki <topic>          → Wikipedia summary + image',
            '.wikipedia <topic>     → alias for .wiki',
            '.urban <word>          → Urban Dictionary slang definition',
        ],
    },
    {
        slug: 'country',
        emoji: '🌍',
        title: 'COUNTRY INFO',
        cmds: [
            '.country <name>',
            '.capital <country>',
            '.flag <country>',
            '.countrytime <country>',
        ],
        help: [
            '.country <name>        → full country info (capital, currency, lang, population)',
            '.capital <country>     → get capital city of a country',
            '.flag <country>        → show country flag image',
            '.countrytime <country> → country timezone(s)',
        ],
    },
    {
        slug: 'animals',
        emoji: '🐾',
        title: 'ANIMALS',
        cmds: [
            '.catfact', '.catimage',
            '.dogfact', '.dogimage',
            '.foximage', '.pandaimage',
            '.koalaimage', '.birb', '.raccoon',
        ],
        help: [
            '.catfact      → random cat fact',
            '.catimage     → random cat image + fact',
            '.dogfact      → random dog fact',
            '.dogimage     → random dog image + fact',
            '.foximage     → random fox image',
            '.pandaimage   → random panda image',
            '.koalaimage   → random koala image',
            '.birb         → random bird image',
            '.raccoon      → random raccoon image',
        ],
    },
    {
        slug: 'food',
        emoji: '🍽️',
        title: 'FOOD & DRINKS',
        cmds: [
            '.recipe <meal>', '.randomrecipe',
            '.cocktail <name>', '.randomcocktail',
        ],
        help: [
            '.recipe <meal>     → search a meal recipe (ingredients + instructions)',
            '.randomrecipe      → random meal recipe',
            '.cocktail <name>   → search a cocktail recipe',
            '.randomcocktail    → alias for .cocktail (random)',
        ],
    },
    {
        slug: 'space',
        emoji: '🌌',
        title: 'SPACE & SCIENCE',
        cmds: [
            '.apod', '.isslocation', '.iss', '.spacefact',
            '.numfact <n>', '.mathfact <n>', '.datefact <m/d>', '.yearfact <yr>',
        ],
        help: [
            '.apod              → NASA Astronomy Picture of the Day',
            '.isslocation / .iss → live International Space Station position',
            '.spacefact         → random space fact',
            '.numfact <n>       → trivia about any number',
            '.mathfact <n>      → math fact about a number',
            '.datefact <m/d>    → historical fact for a date (e.g. .datefact 7/4)',
            '.yearfact <year>   → historical fact for a year',
        ],
    },
    {
        slug: 'texttools',
        emoji: '🔠',
        title: 'TEXT TOOLS',
        cmds: [
            '.reverse <text>', '.morse <text>', '.unmorse <code>',
            '.binary <text>', '.unbinary <bits>',
            '.base64 <text>', '.unbase64 <b64>',
            '.password [len]', '.uuid',
        ],
        help: [
            '.reverse <text>    → reverse any text',
            '.morse <text>      → convert text to Morse code',
            '.unmorse <code>    → decode Morse code to text',
            '.binary <text>     → convert text to binary',
            '.unbinary <bits>   → decode binary to text',
            '.base64 <text>     → Base64 encode',
            '.unbase64 <b64>    → Base64 decode',
            '.password [len]    → generate secure random password (default 16)',
            '.uuid              → generate a random UUID',
        ],
    },
    {
        slug: 'fonts',
        emoji: '✏️',
        title: 'FONT STYLES',
        cmds: [
            '.fancy <text>', '.boldtext <text>', '.italic <text>', '.bolditalic <text>',
            '.script <text>', '.fraktur <text>', '.double <text>',
            '.sans <text>', '.mono <text>', '.wide <text>',
            '.smallcaps <text>', '.bubble <text>',
            '.flip <text>', '.mirror <text>',
        ],
        help: [
            '.fancy <text>      → 𝓯𝓪𝓷𝓬𝔂 script text',
            '.boldtext <text>   → 𝗯𝗼𝗹𝗱 Unicode text',
            '.italic <text>     → 𝘪𝘵𝘢𝘭𝘪𝘤 text',
            '.bolditalic <text> → 𝙗𝙤𝙡𝙙 𝙞𝙩𝙖𝙡𝙞𝙘',
            '.script <text>     → 𝓼𝓬𝓻𝓲𝓹𝓽 style',
            '.fraktur <text>    → 𝔣𝔯𝔞𝔨𝔱𝔲𝔯 Gothic',
            '.double <text>     → 𝕕𝕠𝕦𝕓𝕝𝕖-𝕤𝕥𝕣𝕦𝕔𝕜',
            '.sans <text>       → 𝗌𝖺𝗇𝗌-𝗌𝖾𝗋𝗂𝖿',
            '.mono <text>       → 𝚖𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎',
            '.wide <text>       → ｗｉｄｅ text',
            '.smallcaps <text>  → ꜱᴍᴀʟʟ ᴄᴀᴘꜱ',
            '.bubble <text>     → ⓑⓤⓑⓑⓛⓔ text',
            '.flip <text>       → flip text ʇxǝʇ',
            '.mirror <text>     → txet rorrim',
        ],
    },
    {
        slug: 'generators',
        emoji: '🎲',
        title: 'GENERATORS & GAMES',
        cmds: [
            '.lorem [n]', '.fakename', '.genemail [name]',
            '.randomnum <min> <max>', '.coinflip', '.diceroll [sides]',
            '.riddle', '.riddleanswer',
            '.wouldyou', '.wyr', '.neverhaveiever', '.nhie',
            '.advice', '.yesno',
        ],
        help: [
            '.lorem [n]               → generate Lorem Ipsum sentences',
            '.fakename / .randomperson → random fake identity',
            '.genemail [name]         → generate a fake email address',
            '.randomnum <min> <max>   → random number in a range',
            '.coinflip / .coin        → flip a coin',
            '.diceroll [sides]        → roll a dice (default d6)',
            '.riddle                  → random riddle puzzle',
            '.riddleanswer            → reveal riddle answer',
            '.wouldyou / .wyr         → Would You Rather question',
            '.neverhaveiever / .nhie  → Never Have I Ever prompt',
            '.advice                  → random life advice',
            '.yesno                   → Yes or No with a GIF',
        ],
    },
    {
        slug: 'bible',
        emoji: '✝️',
        title: 'BIBLE & POETRY',
        cmds: [
            '.bible <reference>', '.dailyverse',
            '.poem', '.poetry',
            '.animequote', '.kanye', '.kanyequote',
            '.dadjoke', '.chuck', '.programmingjoke',
            '.yomama', '.darkjoke',
        ],
        help: [
            '.bible <ref>       → fetch any Bible verse (e.g. .bible john 3:16)',
            '.dailyverse        → verse of the day',
            '.poem / .poetry    → random poem from PoetryDB',
            '.animequote        → random anime character quote',
            '.kanye / .kanyequote → random Kanye West quote',
            '.dadjoke           → random dad joke',
            '.chuck             → random Chuck Norris joke',
            '.programmingjoke   → programming / dev joke',
            '.yomama            → yo mama joke',
            '.darkjoke          → dark humour joke',
        ],
    },
    {
        slug: 'converters',
        emoji: '📐',
        title: 'CONVERTERS',
        cmds: [
            '.bmi <kg> <m>', '.age <YYYY-MM-DD>',
            '.celsius <°F>', '.fahrenheit <°C>',
            '.kmtomiles <km>', '.milestokm <mi>',
            '.kgtolbs <kg>', '.lbstokg <lbs>',
        ],
        help: [
            '.bmi <kg> <m>          → BMI calculator + category',
            '.age <YYYY-MM-DD>      → age from birthday in years/months/days',
            '.celsius <°F>          → Fahrenheit to Celsius',
            '.fahrenheit <°C>       → Celsius to Fahrenheit',
            '.kmtomiles <km>        → kilometres to miles',
            '.milestokm <mi>        → miles to kilometres',
            '.kgtolbs <kg>          → kilograms to pounds',
            '.lbstokg <lbs>         → pounds to kilograms',
        ],
    },
    {
        slug: 'manga',
        emoji: '📚',
        title: 'MANGA & MANHWA',
        cmds: [
            '.manga <title>',
            '.manga home',
            '.manga popular [page]',
            '.manga latest [page]',
            '.manga genres',
            '.manga genre <slug> [page]',
            '.manga browse [filters]',
            '.manga details <slug>',
            '.manga read <chapter-slug>',
            '.manga dl <chapter-slug>',
            '.manga dls <slug> <from> <to>',
        ],
        help: [
            '.manga <title>              → search manga, manhwa, manhua',
            '.manga home                 → homepage (popularToday + latestUpdates)',
            '.manga popular [page]       → 🔥 popular titles (paginated)',
            '.manga latest [page]        → 🆕 latest releases (paginated)',
            '.manga genres               → full genre list with slugs',
            '.manga genre <slug> [page]  → browse by genre',
            '.manga browse [filters]     → advanced filter',
            '                              e.g. .manga browse genre=action status=ongoing type=manhwa',
            '.manga details <slug>       → full info + complete chapter list',
            '.manga read <ch-slug>       → chapter page image URLs (reader)',
            '.manga dl <ch-slug>         → download chapter as ZIP (max 30 pages)',
            '.manga dls <slug> <f> <t>   → chapter range ZIP (max 3 chapters)',
            '',
            '📖 Powered by RosyScans via RUNFLIX API',
        ],
    },
    {
        slug: 'groups',
        emoji: '🛡️',
        title: 'GROUP MANAGEMENT',
        cmds: [
            '.kick @user', '.ban @user', '.unban @user', '.add <number>',
            '.promote @user', '.demote @user',
            '.mute', '.unmute', '.mute-user @user', '.unmute-user @user',
            '.warn @user', '.warnings @user', '.clearwarn @user',
            '.del', '.antilink on/off', '.antitag on/off', '.antibadword on/off',
            '.hidetag <msg>', '.tag <msg>', '.tagall',
            '.pin 24h|7d|30d', '.unpin',
            '.welcome on/off', '.goodbye on/off', '.chatbot on/off',
            '.grouplink', '.listadmins', '.listonline', '.membercount',
            '.setgdesc <text>', '.setgname <text>', '.setgpp', '.leave',
        ],
        help: [
            '.kick @user           → remove a member from the group',
            '.ban / .unban @user   → ban or unban a member',
            '.add <number>         → add a number to the group',
            '.promote / .demote    → grant or revoke admin status',
            '.mute / .unmute       → mute or unmute the group',
            '.mute-user @user      → mute a specific user',
            '.warn @user           → issue a warning to a user',
            '.clearwarn @user      → clear a user\'s warnings',
            '.del                  → delete a message (reply to it)',
            '.antilink on/off      → block links posted by members',
            '.antibadword on/off   → block bad words',
            '.antitag on/off       → block mass @tag spam',
            '.hidetag <msg>        → tag all members silently',
            '.tag <msg>            → tag & mention all members',
            '.tagall               → tag every group member',
            '.pin 24h|7d|30d       → pin a message',
            '.unpin                → unpin a message',
            '.grouplink            → get group invite link',
            '.listadmins           → list all group admins',
            '.listonline           → list all group members',
            '.membercount          → group member count breakdown',
            '.welcome on/off       → welcome new members',
            '.goodbye on/off       → farewell message on member leave',
            '.chatbot on/off       → AI-powered group chatbot',
            '.setgdesc / .setgname → change group description/name',
            '.leave                → bot leaves the group',
        ],
    },
    {
        slug: 'owner',
        emoji: '⚙️',
        title: 'OWNER / SYSTEM',
        cmds: [
            '.mode public/private',
            '.anticall on/off', '.pmblocker on/off',
            '.autoread on/off', '.autoreact on/off',
            '.autotyping on/off', '.autostatus on/off', '.savestatus',
            '.afk <reason>', '.antidelete on/off', '.vcf',
            '.block @user', '.unblock @user',
            '.bc <message>', '.broadcast <message>',
            '.clearsession', '.cleartmp',
        ],
        help: [
            '.mode public/private  → set who can use the bot',
            '.anticall on/off      → auto reject incoming calls',
            '.pmblocker on/off     → block unknown private messages',
            '.autoread on/off      → automatically mark messages as read',
            '.autoreact on/off     → automatically react to messages',
            '.autotyping on/off    → show typing indicator',
            '.autostatus on/off    → automatically view statuses',
            '.savestatus           → save status media',
            '.afk <reason>         → set AFK mode with a reason',
            '.antidelete on/off    → detect and show deleted messages',
            '.vcf                  → export group contacts as VCF',
            '.block @user          → block a user',
            '.unblock @user        → unblock a user',
            '.bc <message>         → broadcast message to all contacts',
            '.clearsession         → clear session files',
            '.cleartmp             → clear temp/cache files',
        ],
    },
];

/**
 * Find a category by slug or partial title match.
 */
function findCategory(input) {
    if (!input) return null;
    const q = input.toLowerCase().trim();
    let found = CATEGORIES.find(c => c.slug === q);
    if (found) return found;
    found = CATEGORIES.find(c => c.slug.startsWith(q));
    if (found) return found;
    found = CATEGORIES.find(c =>
        c.title.toLowerCase().split(/[\s&/]+/).some(w => w.startsWith(q))
    );
    if (found) return found;
    found = CATEGORIES.find(c =>
        c.slug.includes(q) || c.title.toLowerCase().includes(q)
    );
    return found || null;
}

CATEGORIES.push({
    slug: 'economy',
    emoji: '💰',
    title: 'ECONOMY',
    cmds: [
        '.balance / .bal',
        '.profile [@user]',
        '.daily',
        '.work',
        '.mine',
        '.fish',
        '.rob @user',
        '.pay @user <amount>',
        '.gift @user <amount>',
        '.deposit <amount/all>',
        '.withdraw <amount/all>',
        '.gamble <amount/all>',
        '.slots <amount>',
        '.coinflip <amount> heads/tails',
        '.store / .shop',
        '.buy <item>',
        '.sell <item>',
        '.inventory / .inv',
        '.equip <item>',
        '.battle @user [bet]',
        '.estats [@user]',
        '.level / .rank / .xp',
        '.quest',
        '.leaderboard / .lb',
        '.addcoins @user amount  (owner)',
        '.removecoins @user amount  (owner)',
        '.resetuser @user  (owner)',
    ],
    help: [
        '── 💰 EARNING ──',
        '.balance / .bal         → check wallet & bank balance',
        '.daily                  → free coins every 24 hours',
        '.work                   → job for coins (1h cooldown)',
        '.mine                   → mine gems/coins (30m cooldown)',
        '.fish                   → fish for coins (20m cooldown)',
        '.quest                  → daily quest reward (24h cooldown)',
        '',
        '── 🏦 BANKING ──',
        '.deposit <amount/all>   → move coins to bank (safe from rob)',
        '.withdraw <amount/all>  → take coins from bank',
        '',
        '── 🤝 SOCIAL ──',
        '.pay @user <amount>     → send coins to someone',
        '.gift @user <amount>    → gift coins to someone',
        '.rob @user              → steal coins — 45% success (2h CD)',
        '',
        '── 🎲 GAMBLING ──',
        '.gamble <amount/all>    → bet coins (45% win)',
        '.slots <amount>         → slot machine (3-match = jackpot)',
        '.coinflip <amt> h/t     → heads or tails bet',
        '',
        '── 🛒 STORE ──',
        '.store / .shop          → view all available items & prices',
        '.buy <item>             → purchase an item',
        '.sell <item>            → sell item back (50% price)',
        '.inventory / .inv       → view your owned items',
        '.equip <item>           → equip weapon / armor / accessory',
        '',
        '── ⚔️ BATTLE ──',
        '.battle @user [bet]     → PvP fight — bet coins on the winner',
        '.estats [@user]         → battle stats, XP, ATK, DEF',
        '',
        '── 🧑 PROFILE ──',
        '.profile [@user]        → full profile card',
        '.level / .xp / .rank    → level progress bar',
        '.leaderboard / .lb      → top 10 richest users',
        '',
        '── 👑 OWNER ONLY ──',
        '.addcoins @user <amt>   → give coins to any user',
        '.removecoins @user <amt>→ deduct coins from any user',
        '.resetuser @user        → wipe a user\'s economy data',
    ],
});

module.exports = { CATEGORIES, findCategory };
